ARG version=ltsc2016
FROM microsoft/windowsservercore:$version

#--------------------------------------------------------------------------------------------------------------
#install chocolatey: see https://github.com/StefanScherer/dockerfiles-windows/blob/master/chocolatey/Dockerfile
#--------------------------------------------------------------------------------------------------------------
RUN powershell -Command \
    iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); \
    choco feature disable --name showDownloadProgress
RUN choco feature enable -n allowGlobalConfirmation

#--------------------------------------------------------------------------------------------------------------
#install node.js LTS
#--------------------------------------------------------------------------------------------------------------
RUN choco install nodejs-lts

#--------------------------------------------------------------------------------------------------------------
#install pdftk (used for PDF concatenation)
#--------------------------------------------------------------------------------------------------------------
RUN choco install pdftk

#--------------------------------------------------------------------------------------------------------------
#install application
#--------------------------------------------------------------------------------------------------------------
ENV EXPRESS_PORT=3000
#optional HTTP request max size (default is 50mb if omitted)
#-----------------------------------------------------------
#ENV EXPRESS_REQUEST_LIMIT=50mb

EXPOSE ${EXPRESS_PORT}

WORKDIR c:/myapp
COPY ./package.json c:/myapp/package.json
COPY ./tsconfig.json c:/myapp/tsconfig.json
COPY ./index.ts c:/myapp/index.ts

#go to myapp dir and finalize install
RUN cd c:\\myapp

#set up node deps
RUN npm install -g typescript
RUN npm install
RUN tsc -p tsconfig.json
CMD ["node","./index.js"]

# NOTES ###########################################################
#to build docker container:
# docker build --rm -f "dockerfile" -t pdf-merge-expressjs:latest .
#
#to run docker container (examples below):
# docker run -p 3000:3000 pdf-merge-expressjs:latest
# docker run -e EXPRESS_REQUEST_LIMIT='100mb' -p 3000:3000 pdf-merge-expressjs:latest
#
###################################################################
